name: smart_chess_app
description: A Flutter app for a smart chess board connected to an ESP32.
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.3
  http: ^1.3.0
  provider: ^6.0.5
  chess: any
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  flutter_appauth: ^2.0.4

  collection: any
  dio: ^5.8.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pieces/
